SpraySite/Controllers/BrowseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SpraySite.DBHelpers;
using SpraySite.Models;

namespace SpraySite.Controllers
{
    public class BrowseController : BaseController
    {

        private static readonly int SPRAYS_PER_PAGE = 15;

        public ActionResult Index()
        {
            return RedirectToAction("Newest");
        }

        public ActionResult Newest(int? after)
        {
            ViewBag.CurrentPage = "browse";
            return View("Gone");

            //ViewBag.BrowseMode = "newest";

            //// Reset to 0 if negative or null
            //int afterSpray = after ?? 0;
            //if (afterSpray < 0) afterSpray = 0;

            //SprayListModel sprays = new SprayListModel();
            //sprays.Start = afterSpray;
            //sprays.Prev = afterSpray - SPRAYS_PER_PAGE < 0 ? 0 : afterSpray - SPRAYS_PER_PAGE;

            //using (var db = new SprayContext())
            //{
            //    sprays.Sprays = db.Sprays.Where(s => s.Safeness == Safeness.SFW).Where(s => s.Status == Status.PUBLIC).OrderByDescending(s => s.DateAdded).Skip(afterSpray).Take(SPRAYS_PER_PAGE).ToList();
            //}

            //sprays.Next = sprays.Sprays.Count < SPRAYS_PER_PAGE ? afterSpray : afterSpray + SPRAYS_PER_PAGE;

            //return View(sprays);
        }

        public ActionResult Top(int? after)
        {
            ViewBag.CurrentPage = "browse";
            return View("Gone");

            //ViewBag.CurrentPage = "browse";
            //ViewBag.BrowseMode = "top";

            //// Reset to 0 if negative or null
            //int afterSpray = after ?? 0;
            //if (afterSpray < 0) afterSpray = 0;

            //SprayListModel sprays = new SprayListModel();
            //sprays.Start = afterSpray;
            //sprays.Prev = afterSpray - SPRAYS_PER_PAGE < 0 ? 0 : afterSpray - SPRAYS_PER_PAGE;

            //using (var db = new SprayContext())
            //{
            //    sprays.Sprays = db.Sprays.Where(s => s.Safeness == Safeness.SFW).Where(s => s.Status == Status.PUBLIC).OrderByDescending(s => s.Saves).Skip(afterSpray).Take(SPRAYS_PER_PAGE).ToList();
            //}

            //sprays.Next = sprays.Sprays.Count < SPRAYS_PER_PAGE ? afterSpray : afterSpray + SPRAYS_PER_PAGE;

            //return View(sprays);
        }

        public ActionResult NewestNSFW(int? after)
        {
            ViewBag.AdultAds = true;
            ViewBag.CurrentPage = "browse";
            return View("Gone");

            //ViewBag.CurrentPage = "browse";
            //ViewBag.BrowseMode = "newestnsfw";

            //// Reset to 0 if negative or null
            //int afterSpray = after ?? 0;
            //if (afterSpray < 0) afterSpray = 0;

            //SprayListModel sprays = new SprayListModel();
            //sprays.Start = afterSpray;
            //sprays.Prev = afterSpray - SPRAYS_PER_PAGE < 0 ? 0 : afterSpray - SPRAYS_PER_PAGE;

            //using (var db = new SprayContext())
            //{
            //    sprays.Sprays = db.Sprays.Where(s => s.Safeness == Safeness.NSFW).Where(s => s.Status == Status.PUBLIC).OrderByDescending(s => s.DateAdded).Skip(afterSpray).Take(SPRAYS_PER_PAGE).ToList();
            //}

            //sprays.Next = sprays.Sprays.Count < SPRAYS_PER_PAGE ? afterSpray : afterSpray + SPRAYS_PER_PAGE;

            //return View(sprays);
        }

        public ActionResult TopNSFW(int? after)
        {
            ViewBag.AdultAds = true;
            ViewBag.CurrentPage = "browse";
            return View("Gone");

            //ViewBag.CurrentPage = "browse";
            //ViewBag.BrowseMode = "topnsfw";

            //// Reset to 0 if negative or null
            //int afterSpray = after ?? 0;
            //if (afterSpray < 0) afterSpray = 0;

            //SprayListModel sprays = new SprayListModel();
            //sprays.Start = afterSpray;
            //sprays.Prev = afterSpray - SPRAYS_PER_PAGE < 0 ? 0 : afterSpray - SPRAYS_PER_PAGE;

            //using (var db = new SprayContext())
            //{
            //    sprays.Sprays = db.Sprays.Where(s => s.Safeness == Safeness.NSFW).Where(s => s.Status == Status.PUBLIC).OrderByDescending(s => s.Saves).Skip(afterSpray).Take(SPRAYS_PER_PAGE).ToList();
            //}

            //sprays.Next = sprays.Sprays.Count < SPRAYS_PER_PAGE ? afterSpray : afterSpray + SPRAYS_PER_PAGE;

            //return View(sprays);
        }

        public ActionResult NewestSketchy(int? after)
        {
            ViewBag.CurrentPage = "browse";
            return View("Gone");

            //ViewBag.CurrentPage = "browse";
            //ViewBag.BrowseMode = "newestsketchy";

            //// Reset to 0 if negative or null
            //int afterSpray = after ?? 0;
            //if (afterSpray < 0) afterSpray = 0;

            //SprayListModel sprays = new SprayListModel();
            //sprays.Start = afterSpray;
            //sprays.Prev = afterSpray - SPRAYS_PER_PAGE < 0 ? 0 : afterSpray - SPRAYS_PER_PAGE;

            //using (var db = new SprayContext())
            //{
            //    sprays.Sprays = db.Sprays.Where(s => s.Safeness == Safeness.SKETCHY).Where(s => s.Status == Status.PUBLIC).OrderByDescending(s => s.DateAdded).Skip(afterSpray).Take(SPRAYS_PER_PAGE).ToList();
            //}

            //sprays.Next = sprays.Sprays.Count < SPRAYS_PER_PAGE ? afterSpray : afterSpray + SPRAYS_PER_PAGE;

            //return View(sprays);
        }

        public ActionResult TopSketchy(int? after)
        {
            ViewBag.CurrentPage = "browse";
            return View("Gone");

            //ViewBag.CurrentPage = "browse";
            //ViewBag.BrowseMode = "topsketchy";

            //// Reset to 0 if negative or null
            //int afterSpray = after ?? 0;
            //if (afterSpray < 0) afterSpray = 0;

            //SprayListModel sprays = new SprayListModel();
            //sprays.Start = afterSpray;
            //sprays.Prev = afterSpray - SPRAYS_PER_PAGE < 0 ? 0 : afterSpray - SPRAYS_PER_PAGE;

            //using (var db = new SprayContext())
            //{
            //    sprays.Sprays = db.Sprays.Where(s => s.Safeness == Safeness.SKETCHY).Where(s => s.Status == Status.PUBLIC).OrderByDescending(s => s.Saves).Skip(afterSpray).Take(SPRAYS_PER_PAGE).ToList();
            //}

            //sprays.Next = sprays.Sprays.Count < SPRAYS_PER_PAGE ? afterSpray : afterSpray + SPRAYS_PER_PAGE;

            //return View(sprays);
        }

        public ActionResult Mine(int? after)
        {
            if (!Request.IsAuthenticated)
            {
                return View("Error");
            }

            ViewBag.CurrentPage = "mine";

            // Reset to 0 if negative or null
            int afterSpray = after ?? 0;
            if (afterSpray < 0) afterSpray = 0;

            SprayListModel sprays = new SprayListModel();
            sprays.Start = afterSpray;
            sprays.Prev = afterSpray - SPRAYS_PER_PAGE < 0 ? 0 : afterSpray - SPRAYS_PER_PAGE;

            using (var db = new SprayContext())
            {
                long steamId64 = long.Parse(User.Identity.Name);

                sprays.Sprays = db.Sprays.Where(s => s.Creator.SteamId == steamId64).Where(s => s.Status != Status.DELETED).OrderByDescending(s => s.DateAdded).Skip(afterSpray).Take(SPRAYS_PER_PAGE).ToList();
            }

            sprays.Next = sprays.Sprays.Count < SPRAYS_PER_PAGE ? afterSpray : afterSpray + SPRAYS_PER_PAGE;

            return View(sprays);
        }

        public ActionResult Saved(int? after)
        {
            if (!Request.IsAuthenticated)
            {
                return View("Error");
            }

            ViewBag.CurrentPage = "saved";

            // Reset to 0 if negative or null
            int afterSpray = after ?? 0;
            if (afterSpray < 0) afterSpray = 0;

            SprayListModel sprays = new SprayListModel();
            sprays.Start = afterSpray;
            sprays.Prev = afterSpray - SPRAYS_PER_PAGE < 0 ? 0 : afterSpray - SPRAYS_PER_PAGE;

            using (var db = new SprayContext())
            {
                long steamId64 = long.Parse(User.Identity.Name);

                sprays.Sprays = db.Users.Where(u => u.SteamId == steamId64).First().Saved.Where(s => s.Status != Status.DELETED).Where(s => s.Status != Status.ACTIVE).OrderByDescending(s => s.DateAdded).Skip(afterSpray).Take(SPRAYS_PER_PAGE).ToList();
            }

            sprays.Next = sprays.Sprays.Count < SPRAYS_PER_PAGE ? afterSpray : afterSpray + SPRAYS_PER_PAGE;

            return View(sprays);
        }

    }
}

SpraySite/Views/Browse/BrowseNav.cshtml
<h2>Browse Sprays</h2>

<ul class="nav nav-pills">
    <li class="@(ViewBag.BrowseMode == "newest" ? "active" : "")">
        <a href="@Url.Action("Newest", "Browse")">Newest</a>
    </li>
    <li class="@(ViewBag.BrowseMode == "top" ? "active" : "")">
        <a href="@Url.Action("Top", "Browse")">Top Saved</a>
    </li>
    
    <li class="@(ViewBag.BrowseMode == "newestsketchy" ? "active" : "")">
        <a href="@Url.Action("NewestSketchy", "Browse")">Newest Sketchy</a>
    </li>
    <li class="@(ViewBag.BrowseMode == "topsketchy" ? "active" : "")">
        <a href="@Url.Action("TopSketchy", "Browse")">Top Saved Sketchy</a>
    </li>
    
    <li class="@(ViewBag.BrowseMode == "newestnsfw" ? "active" : "")">
        <a href="@Url.Action("NewestNSFW", "Browse")">Newest NSFW</a>
    </li>
    <li class="@(ViewBag.BrowseMode == "topnsfw" ? "active" : "")">
        <a href="@Url.Action("TopNSFW", "Browse")">Top Saved NSFW</a>
    </li>
</ul>

SpraySite/Views/Browse/Gone.cshtml
@{
    ViewBag.Title = "Browse Sprays - Spray Maker v3";
}

<div class="hero-unit">
  <h1>TFSprays Gallery is no longer available</h1>
  <p></p>
  <p><b>Q: Why is the gallery gone?</b></p>
  <p>A: Because it was costing me over $100/mo in bandwidth, when I am only getting ~$20 (if that) in ad revenue. This hobby is quickly becoming way too expensive.</p>

  <p><b>Q: Where can I find sprays now?</b></p>
  <p>A: I suggest <a href="http://tf2.gamebanana.com/sprays">GameBanana</a> or <a href="http://gamesprays.com">Game Sprays</a>.</p>

  <p><b>Q: Can I still make sprays?</b></p>
  <p>A: Yes.</p>

  <p><b>Q: Can I still share the sprays I make?</b></p>
  <p>A: Yeah! Sprays can be marked as "public", like always. "Unlisted" is going away, since all public sprays are technically unlisted.</p>

  <p><b>Q: Can I donate money to keep the gallery here?</b></p>
  <p>A: No -- unless you want to pay $80 a month...</p>

  <p><b>Q: Can't you just put more ads on?</b></p>
  <p>A: No.</p>

  <p><b>Q: I want to complain!</b></p>
  <p>A: That's not a question. But you can tweet @@cjung.</p>
</div>

SpraySite/Views/Browse/Mine.cshtml
@model SpraySite.Models.SprayListModel

@{
    ViewBag.Title = "My Sprays - Spray Maker v3";
}

<h2>My Sprays</h2>

@if (Model.Sprays.Count == 0)
{
    <p class="lead">You haven't made any sprays! <a href="@Url.Action("Static", "Create")">Make one now?</a></p>
}

@Html.Partial("BrowseLoop")

<ul class="pager">
    @if (Model.Start == 0){
        <li class="disabled"><a href="#">Newer</a></li> 
    } 
    else
    {
        <li><a href="@Url.Action("Mine", "Browse", new { after = Model.Prev })">Newer</a></li>   
    }

    @if (Model.Start == Model.Next){
        <li class="disabled"><a href="#">Older</a></li> 
    } 
    else
    {
        <li><a href="@Url.Action("Mine", "Browse", new { after = Model.Next })">Older</a></li>
    }
</ul>

SpraySite/Views/Browse/Newest.cshtml
@model SpraySite.Models.SprayListModel

@{
    ViewBag.Title = "Browse Sprays - Spray Maker v3";
}

@Html.Partial("BrowseNav")

@Html.Partial("BrowseLoop")

<ul class="pager">
    @if (Model.Start == 0){
        <li class="disabled"><a href="#">Newer</a></li> 
    } 
    else
    {
        <li><a href="@Url.Action("Newest", "Browse", new { after = Model.Prev })">Newer</a></li>   
    }

    @if (Model.Start == Model.Next){
        <li class="disabled"><a href="#">Older</a></li> 
    } 
    else
    {
        <li><a href="@Url.Action("Newest", "Browse", new { after = Model.Next })">Older</a></li>
    }
</ul>

SpraySite/Views/Browse/NewestNSFW.cshtml
@model SpraySite.Models.SprayListModel

@{
    ViewBag.Title = "Browse Sprays - Spray Maker v3";
}

@Html.Partial("BrowseNav")

@Html.Partial("BrowseLoop")

<ul class="pager">
    @if (Model.Start == 0){
        <li class="disabled"><a href="#">Newer</a></li> 
    } 
    else
    {
        <li><a href="@Url.Action("NewestNSFW", "Browse", new { after = Model.Prev })">Newer</a></li>   
    }

    @if (Model.Start == Model.Next){
        <li class="disabled"><a href="#">Older</a></li> 
    } 
    else
    {
        <li><a href="@Url.Action("NewestNSFW", "Browse", new { after = Model.Next })">Older</a></li>
    }
</ul>

SpraySite/Views/Browse/NewestSketchy.cshtml
@model SpraySite.Models.SprayListModel

@{
    ViewBag.Title = "Browse Sprays - Spray Maker v3";
}

@Html.Partial("BrowseNav")

@Html.Partial("BrowseLoop")

<ul class="pager">
    @if (Model.Start == 0){
        <li class="disabled"><a href="#">Newer</a></li> 
    } 
    else
    {
        <li><a href="@Url.Action("NewestSketchy", "Browse", new { after = Model.Prev })">Newer</a></li>   
    }

    @if (Model.Start == Model.Next){
        <li class="disabled"><a href="#">Older</a></li> 
    } 
    else
    {
        <li><a href="@Url.Action("NewestSketchy", "Browse", new { after = Model.Next })">Older</a></li>
    }
</ul>

SpraySite/Views/Browse/Saved.cshtml
@model SpraySite.Models.SprayListModel

@{
    ViewBag.Title = "Saved Sprays - Spray Maker v3";
}

<h2>Saved Sprays</h2>
@if (Model.Sprays.Count == 0)
{
    <p class="lead">You haven't saved any sprays! Why don't you <a href="@Url.Action("Top", "Browse")">look for some?</a></p>
}

@Html.Partial("BrowseLoop")

<ul class="pager">
    @if (Model.Start == 0){
        <li class="disabled"><a href="#">Newer</a></li> 
    } 
    else
    {
        <li><a href="@Url.Action("Saved", "Browse", new { after = Model.Prev })">Newer</a></li>   
    }

    @if (Model.Start == Model.Next){
        <li class="disabled"><a href="#">Older</a></li> 
    } 
    else
    {
        <li><a href="@Url.Action("Saved", "Browse", new { after = Model.Next })">Older</a></li>
    }
</ul>

SpraySite/Views/Browse/Top.cshtml
@model SpraySite.Models.SprayListModel

@{
    ViewBag.Title = "Browse Sprays - Spray Maker v3";
}

@Html.Partial("BrowseNav")

@Html.Partial("BrowseLoop")

<ul class="pager">
    @if (Model.Start == 0){
        <li class="disabled"><a href="#">More Saves</a></li> 
    } 
    else
    {
        <li><a href="@Url.Action("Top", "Browse", new { after = Model.Prev })">More Saves</a></li>   
    }

    @if (Model.Start == Model.Next){
        <li class="disabled"><a href="#">Fewer Saves</a></li> 
    } 
    else
    {
        <li><a href="@Url.Action("Top", "Browse", new { after = Model.Next })">Fewer Saves</a></li>
    }
</ul>

SpraySite/Views/Browse/TopNSFW.cshtml
@model SpraySite.Models.SprayListModel

@{
    ViewBag.Title = "Browse Sprays - Spray Maker v3";
}

@Html.Partial("BrowseNav")

@Html.Partial("BrowseLoop")

<ul class="pager">
    @if (Model.Start == 0){
        <li class="disabled"><a href="#">More Saves</a></li> 
    } 
    else
    {
        <li><a href="@Url.Action("TopNSFW", "Browse", new { after = Model.Prev })">More Saves</a></li>   
    }

    @if (Model.Start == Model.Next){
        <li class="disabled"><a href="#">Fewer Saves</a></li> 
    } 
    else
    {
        <li><a href="@Url.Action("TopNSFW", "Browse", new { after = Model.Next })">Fewer Saves</a></li>
    }
</ul>

SpraySite/Views/Browse/TopSketchy.cshtml
@model SpraySite.Models.SprayListModel

@{
    ViewBag.Title = "Browse Sprays - Spray Maker v3";
}

@Html.Partial("BrowseNav")

@Html.Partial("BrowseLoop")

<ul class="pager">
    @if (Model.Start == 0){
        <li class="disabled"><a href="#">More Saves</a></li> 
    } 
    else
    {
        <li><a href="@Url.Action("TopSketchy", "Browse", new { after = Model.Prev })">More Saves</a></li>   
    }

    @if (Model.Start == Model.Next){
        <li class="disabled"><a href="#">Fewer Saves</a></li> 
    } 
    else
    {
        <li><a href="@Url.Action("TopSketchy", "Browse", new { after = Model.Next })">Fewer Saves</a></li>
    }
</ul>