SpraySite/Controllers/SprayController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SpraySite.DBHelpers;
using SpraySite.Models;

namespace SpraySite.Controllers
{
    public class SprayController : BaseController
    {

        public ActionResult Index()
        {
            return RedirectToAction("All", "Browse");
        }

        public ActionResult ViewSpray(string id)
        {
            ViewBag.CurrentPage = "browse";

            Guid providedId;
            if (!Guid.TryParse(id, out providedId))
            {
                return View("Error");
            }

            Spray spray;
            bool saved = false;
            bool mine = false;
            using (var db = new SprayContext())
            {
                spray = db.Sprays.Where(s => s.Id == providedId).FirstOrDefault();

                if (Request.IsAuthenticated)
                {
                    long steamId64 = long.Parse(User.Identity.Name);
                    if (spray.SavedBy.Where(u => u.SteamId == steamId64).Count() != 0)
                        saved = true;

                    if (spray.Creator != null && spray.Creator.SteamId == steamId64)
                        mine = true;
                }

                // Don't show unapproved sprays
                if (spray.Status == Status.ACTIVE && !mine)
                {
                    spray = null;
                }

            }

            if (spray == null)
                return View("Error");

            if(spray.Safeness == Safeness.NSFW)
                ViewBag.AdultAds = true;

            return View("View", new SprayViewModel { Spray = spray, SavedByCurrent = saved, IsCurrentUsersSpray = mine });
        }

        public ActionResult Save(string id)
        {
            if (Request.IsAuthenticated)
            {
                Guid providedId;
                if (!Guid.TryParse(id, out providedId))
                {
                    return View("Error");
                }

                using (var db = new SprayContext())
                {
                    Spray spray = db.Sprays.Where(s => s.Id == providedId).Where(s => s.Status != Status.DELETED).Where(s => s.DateExpires > DateTime.Now).ToList().FirstOrDefault();
                    if (spray != null)
                    {
                        long steamId64 = long.Parse(User.Identity.Name);
                        User u = db.Users.FirstOrDefault(x => x.SteamId == steamId64);

                        if (!u.Saved.Contains(spray))
                        {
                            u.Saved.Add(spray);
                            spray.Saves++;

                            db.SaveChanges();
                        }
                    }

                    return RedirectToRoute("View Spray");

                }
            }
            else
            {
                return View("Error");
            }
        }

        public ActionResult Unsave(string id)
        {
            if (Request.IsAuthenticated)
            {
                Guid providedId;
                if (!Guid.TryParse(id, out providedId))
                {
                    return View("Error");
                }

                using (var db = new SprayContext())
                {
                    Spray spray = db.Sprays.Where(s => s.Id == providedId).FirstOrDefault();
                    if (spray != null)
                    {
                        long steamId64 = long.Parse(User.Identity.Name);
                        User u = db.Users.FirstOrDefault(x => x.SteamId == steamId64);

                        if(u.Saved.Contains(spray)){
                            u.Saved.Remove(spray);
                            spray.Saves--;

                            db.SaveChanges();
                        }
                    }

                    return RedirectToRoute("View Spray");

                }
            }
            else
            {
                return View("Error");
            }
        }

        public ActionResult Privatize(string id)
        {
            if (Request.IsAuthenticated)
            {
                Guid providedId;
                if (!Guid.TryParse(id, out providedId))
                {
                    return View("Error");
                }

                using (var db = new SprayContext())
                {
                    Spray spray = db.Sprays.Where(s => s.Id == providedId).FirstOrDefault();
                    if (spray != null)
                    {
                        long steamId64 = long.Parse(User.Identity.Name);

                        if (spray.Creator.SteamId == steamId64 || User.Identity.Name == "76561197999489042") /* CHANGEME - This is my Steam ID. If I logged in, I got extra admin options */
                        {
                            spray.Status = Status.ACTIVE;
                            db.SaveChanges();
                        }
                    }

                    return RedirectToRoute("View Spray");

                }
            }
            else
            {
                return View("Error");
            }
        }

        public ActionResult Unlist(string id)
        {
            if (Request.IsAuthenticated)
            {
                Guid providedId;
                if (!Guid.TryParse(id, out providedId))
                {
                    return View("Error");
                }

                using (var db = new SprayContext())
                {
                    Spray spray = db.Sprays.Where(s => s.Id == providedId).FirstOrDefault();
                    if (spray != null)
                    {
                        long steamId64 = long.Parse(User.Identity.Name);

                        if (spray.Creator.SteamId == steamId64 || User.Identity.Name == "76561197999489042") /* CHANGEME - This is my Steam ID. If I logged in, I got extra admin options */
                        {
                            spray.Status = Status.UNLISTED;
                            db.SaveChanges();
                        }
                    }

                    return RedirectToRoute("View Spray");

                }
            }
            else
            {
                return View("Error");
            }
        }

        public ActionResult Publish(string id)
        {
            if (Request.IsAuthenticated)
            {
                Guid providedId;
                if (!Guid.TryParse(id, out providedId))
                {
                    return View("Error");
                }

                using (var db = new SprayContext())
                {
                    Spray spray = db.Sprays.Where(s => s.Id == providedId).FirstOrDefault();
                    if (spray != null)
                    {
                        long steamId64 = long.Parse(User.Identity.Name);

                        /* CHANGEME - This is my Steam ID. If I logged in, I got extra admin options */
                        if ((spray.Creator.SteamId == steamId64 || User.Identity.Name == "76561197999489042") && spray.Status != Status.PUBLIC) // So we don't have to re-moderate
                        {
                            spray.Status = Status.UNMODERATED;
                            db.SaveChanges();
                        }
                    }

                    return RedirectToRoute("View Spray");

                }
            }
            else
            {
                return View("Error");
            }
        }

        public ActionResult Delete(string id)
        {
            if (Request.IsAuthenticated)
            {
                Guid providedId;
                if (!Guid.TryParse(id, out providedId))
                {
                    return View("Error");
                }

                using (var db = new SprayContext())
                {
                    Spray spray = db.Sprays.Where(s => s.Id == providedId).FirstOrDefault();
                    if (spray != null)
                    {
                        long steamId64 = long.Parse(User.Identity.Name);

                        if (spray.Creator.SteamId == steamId64 || User.Identity.Name == "76561197999489042") /* CHANGEME - This is my Steam ID. If I logged in, I got extra admin options */
                        {
                            spray.Status = Status.DELETED;
                            db.SaveChanges();
                        }
                    }

                    return RedirectToAction("Mine", "Browse");

                }
            }
            else
            {
                return View("Error");
            }
        }

    }
}

SpraySite/Views/Shared/BrowseLoop.cshtml
@model SpraySite.Models.SprayListModel

@for (int i = 0; i < Model.Sprays.Count; i++)
{
    
    if (i % 3 == 0)
    {
        @:<div class="row">
    }

    <div class="span4">
        <div class="previewContainer">
            <a href="@Url.Action(Model.Sprays.ElementAt(i).Id.ToString(), "Spray")">
                <div class="imageWrapper">
                    <div class="flagContainer">
                        @if (Model.Sprays.ElementAt(i).Fading)
                        {
                            <span class="label label-success fadingFlag" title="Fading"><i class="icon-random icon-white"></i></span>
                        }

                        @if (Model.Sprays.ElementAt(i).Animated)
                        {
                            <span class="label label-info animatedFlag" title="Animated"><i class="icon-play icon-white"></i></span>
                        }

                        @if (Model.Sprays.ElementAt(i).Safeness == SpraySite.Models.Safeness.SKETCHY)
                        {
                            <span class="label label-warning nsfwFlag"><i class="icon-eye-open icon-white"></i> SKETCHY</span>
                        }

                        @if (Model.Sprays.ElementAt(i).Safeness == SpraySite.Models.Safeness.NSFW)
                        {
                            <span class="label label-important nsfwFlag"><i class="icon-eye-open icon-white"></i> NSFW</span>
                        }

                        @if (Model.Sprays.ElementAt(i).Saves > 0)
                        {
                            <span class="label label-warning savesFlag" title="Saves"><i class="icon-star icon-white"></i> @Model.Sprays.ElementAt(i).Saves</span>
                        }

                    </div>
                    <div class="imageDiv farImage">
                        <img src="@Model.Sprays.ElementAt(i).PreviewImage" alt="@Model.Sprays.ElementAt(i).Id Preview" />
                    </div>

                    @if (Model.Sprays.ElementAt(i).Fading)
                    {
                        <div class="imageDiv nearImage">
                            <img src="@Model.Sprays.ElementAt(i).PreviewImageNear" alt="@Model.Sprays.ElementAt(i).Id Near Preview" />
                        </div>
                    }
                </div>
            </a>
        </div>
    </div>
    
    if (i % 3 == 2 || i == Model.Sprays.Count - 1)
    {
        @:</div>
    }

}

SpraySite/Views/Shared/Error404.cshtml
@{
    ViewBag.Title = "Error - Spray Maker v3";
}

<h1 class="text-center">Oh no!</h1>
<h2 class="text-center">That page doesn't exist!</h2>
<img src="@Url.Content("~/Content/images/404_cat.jpg")" class="img-polaroid" />
<h3 class="text-center">In the meantime, here's a picture of a cat in a hat!</h3>
<div class="text-center">
    <small>(Thanks, <a href="http://www.flickr.com/photos/catsintrees/3766803628/">Cats in trees</a>!)</small>
</div>

SpraySite/Views/Shared/Maintenance.cshtml
@{
    ViewBag.Title = "Read Only Mode - Spray Maker v3";
}

<h1 class="text-center">TFSprays is currently in read-only mode.</h1>
<h2 class="text-center">We'll be back as soon as possible!</h2>
<img src="@Url.Content("~/Content/images/error_cat.jpg")" class="img-polaroid" />
<h3 class="text-center">In the meantime, here's a picture of a cat in a hat!</h3>
<div class="text-center">
    <small>(Thanks, <a href="http://www.flickr.com/photos/29233640@N07/5770462910/">Robert Couse-Baker</a>!)</small>
</div>

SpraySite/Views/Shared/_Ads.cshtml
<!-- Project Wonderful Ad Box Loader -->
<!-- Put this after the <body> tag at the top of your page -->
<script type="text/javascript">
   (function(){function pw_load(){
      if(arguments.callee.z)return;else arguments.callee.z=true;
      var d=document;var s=d.createElement('script');
      var x=d.getElementsByTagName('script')[0];
      s.type='text/javascript';s.async=true;
      s.src='//www.projectwonderful.com/pwa.js';
      x.parentNode.insertBefore(s,x);}
   if (window.attachEvent){
    window.attachEvent('DOMContentLoaded',pw_load);
    window.attachEvent('onload',pw_load);}
   else{
    window.addEventListener('DOMContentLoaded',pw_load,false);
    window.addEventListener('load',pw_load,false);}})();
</script>
<!-- End Project Wonderful Ad Box Loader -->

SpraySite/Views/Shared/_Footer.cshtml
<div class="row" id="footer">
    <div class="span12">

        @if(ViewBag.AdultAds != true && ViewBag.NoAds != true)
        {
        <div class="well well-small">
            <!-- CHANGEME - Regular ads go here -->
        </div>
        } else if(ViewBag.NoAds != true) {
            <div class="well well-small">
            <!-- CHANGEME - "Adult" ad code goes here -->
            </div>
        } else {
        }

        <div class="well well-small">
            <small>TF2 Spray Maker is not affiliated with Valve or TeamFortress.com (may they never go hatless). The TF2 logo is property of Valve. All content is user-uploaded and is copyright its original owner.
            If you would like your intellectual property removed, please contact dmca a codyjung d com.
            </small>
        </div>
    </div>
</div>

SpraySite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/bootstrap")
    @Styles.Render("~/Content/css")
</head>
<body>
    @Html.Partial("_Ads")
    @Html.Partial("_Navigation")

@*<div class="alert alert-info text-center">
    <strong>Do you speak Korean? I don't!</strong> 한국어로이 사이트를 번역! <a href="https://bitbucket.org/CodyJung/spraymakerv3/issue/23/provide-korean-site-translation">Comment here if you want to help translate the site!</a>
</div>*@

    @*<div class="alert alert-info text-center">
        <strong>Where's the gallery?</strong> - <a href="/Browse/Newest">Click here for more info</a>
    </div>*@

    <div class="container">
        @RenderBody()

        @Html.Partial("_Footer")
    </div>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    @Scripts.Render("~/bundles/signalr")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/smjs")
    <script type="text/javascript" src="@Url.Content("/signalr/hubs")"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

SpraySite/Views/Shared/_Navigation.cshtml
<div class="navbar navbar-inverse navbar-static-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="brand" href="@Url.Action("Index", "Home")"><img alt="Spray Maker - Home" src="@Url.Content("~/Content/Images/logo.png")" width="17" height="20" /> Spray Maker</a>

            <ul class="nav">
@*                <li class="@(ViewBag.CurrentPage == "default" ? "active" : "")">
                    <a href="@Url.Action("Index", "Home")">Home</a>
                </li>*@

                <li class="@(ViewBag.CurrentPage == "create" ? "active" : "")">
                    <a href="@Url.Action("Static", "Create")">Create a Spray</a>
                </li>

                <li class="@(ViewBag.CurrentPage == "createFading" ? "active" : "")">
                    <a href="@Url.Action("Fading", "Create")">Create a Fading Spray</a>
                </li>

                @*<li class="@(ViewBag.CurrentPage == "browse" ? "active" : "")">
                    <a href="@Url.Action("Newest", "Browse")">Browse Gallery</a>
                </li>*@

                @if(Request.IsAuthenticated)
                {
                <li class="@(ViewBag.CurrentPage == "saved" ? "active" : "")">
                    <a href="@Url.Action("Saved", "Browse")">Saved Sprays</a>
                </li>

                <li class="@(ViewBag.CurrentPage == "mine" ? "active" : "")">
                    <a href="@Url.Action("Mine", "Browse")">My Sprays</a>
                </li>
                }
            </ul>

            <ul class="nav pull-right">

                @if (Request.IsAuthenticated)
                {
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">@ViewBag.UserName<b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">

                            <li>
                                <a href="@Url.Action("LogOff", "Account")">Log Off</a>
                            </li>
                        </ul>
                    </li>
                    
                    <li><span class="brand" data-toggle="dropdown">
                        <img src="@ViewBag.AvatarUrl" alt="User avatar" width="23" height="23" border="0" /></span>
                    </li>
                        
                }
                else
                {
                    <li>
                        <a class="brand" href="@Url.Action("OpenId", "Account")">
                            <img src="@Url.Content("~/Content/Images/sits_small.png")" alt="Sign in through Steam" width="154" height="23" border="0" /></a>
                    </li>
                }
            </ul>
        </div>
    </div>
</div>